name: whitebox-environment
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - matplotlib
  - imageio
  - pip:
    - whitebox
    - tifffile
    - requests
    - googledrivedownloader

